# Snowpack and Avalanches

Turnagain Pass has a maritime snowpack, receiving hundreds of inches of
snow (and often, rain) a year.

The local avalanche center is
[CNFAIC](https://www.cnfaic.org/forecast/turnagain/)
(Chugach National Forest Avalanche Information Center).

## Ground Hoar

We don't usually get it. Hurray! So that means we don't usually have to
worry about avalanches breaking at the ground.

## Glide Cracks

We DO have a hazard that is a lot less common in other zones: glide cracks.
This is when the entire snowpack creeps along the ground, and a glide crack appears
where sections separate.
They are more likely to be active during warm periods and rain, but they can
still be active at other times too.

They present as a 1-10 foot wide gap in the snowpack that is open all the
way to the ground below, which can sometimes be 10 or 15 feet below.
This is one hazard of them: if you are careless or if the visibility is bad,
you can ski off a non-insignificant temporary cliff!

They also are hazards when they release as catastrophic avalanches.
This actually is pretty rare, most glide cracks we see become inactive
and then new snow fills in the crack.
But when they do release, they release usually to the ground, and very large.
Usually you can't trigger them yourself, but you just want to minimize
your exposure by not lingering underneath them.

In general

- try to avoid them if you can
- be especially cautious in bad visibility
- if there is no better route, I wouldn't think it was crazy to quickly scoot
  around them
