project:
  type: book
  resources:
    - "assets/*"

book:
  title: "Turn, Again"
  subtitle: "A Backcountry Ski Guide to Turnagain Pass, Alaska"
  license: "Public Domain"
  sidebar:
    logo: assets/cover.jpg
  favicon: assets/favicon.png
  page-navigation: true
  downloads: [pdf]
  repo-url: https://github.com/NickCrews/turnagain-guide
  repo-actions: [edit]
  page-footer:
    center: 
      - text: "About"
        href: chapters/about.qmd
      - text: "License"
        href: chapters/license.qmd
  chapters:
    - index.qmd
    - chapters/conditions.qmd
    - part: General Information
      chapters:
        - chapters/general/terrain-weather-snowpack.qmd
        - chapters/general/resources.qmd
    - part: Areas
      chapters:
        - chapters/areas/overview.qmd
        - chapters/areas/eddies.qmd
        - chapters/areas/tincan.qmd
        - chapters/areas/sunburst.qmd
        - chapters/areas/magnum.qmd
        - chapters/areas/lipps.qmd
        - chapters/areas/petes.qmd


format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    documentclass: scrreprt



