# Tincan

Tincan is the most popular area in Turnagain Pass, and one of the most popular areas in all of Alaska.

There is a wide selection of terrain available.

## Parking

There is a pulloff on the East side of the highway, on the outside of a curve.
It is one of the better-plowed parking lots in Turnagain pass,
usually plowed either during or the day after a storm.

This is a dangerous parking lot. In 2021 (???), a semi truck slid off the road
and pancaked three cars that were parked in the lot, as Mark Jonas and Bob Dugan
were putting on their skins.
I try to not linger in the parking lot for very long after I park,
and put on my gear near the guardrail where I am at least marginally protected
by the parked cars.

Once you park, it's a chaotic scramble/slide down the embankment and across the meadow.
On the far side of a meadow, CNFAIC usually has a beacon checker machine.
Slide past it one at a time to verify that your beacon is working.

If you want a break from downhill skiing, on a clear day it is fun to nordic ski
North through these meadows.
You go gradually uphill until you reach a crest where
you are treated to a beautiful view down the length of the whole of Turnagain Pass,
all the way down to Turnagain Arm 1000 feet below.
You better watch out though, or you might run into a roving band of retired ladies
from Girdwood drinking gin and tonics and eating cake for someone's birthday.

Very very rarely is the parking lot so full that there is no room.
When this happens, choose a different zone, or continue South up the highway
to the Center Ridge parking lot, and you can access the Tincan ridge from the slightly
longer and lower quality "Blue Diamond" approach trail.

## Approach

Cross the parking lot meadow and then head basically up the fall line to the ridge,
and then continue following that. See the GPS track.
You will almost always have some track to follow.

The skintrack is generally low angle and fairly easy.
It continues all the way to very near the sumimit, the starting point of Tincan Common.
You are out of large-scale avalanche terrain the entire time.
There are a few small but steep rollovers that I might be concerned
about on the highest danger days, but in general it is very safe.
If it's a high danger but good weather, a very nice route is
to skin all the way to the top of Tincan Common, enjoy the awesome views,
and ski right back down the skintrack.

## Deproach

The most surefire way to get back to the parking lot is to reverse the
main uptrack, skiing down the ridge the whole way.

If you are at the bottom of Tincan Trees, there is also a deproach track that takes
you back to the parking lot with only minimal scooching along a few flat meadows.
This is the most popular way to deproach Tincan.
The benefit of this route is that it allows for slightly better skiing
through tin can trees on your last descent; the skiing down the ridge is slightly worse.
The downside of this route is that it can be confusing if you don't know where
you are going.
Usually you will find a track from others before you,
although if it hasn't snowed recently these tracks can become a maze
of people skiing and skinning in all different directions.
If you follow the GPS track you will be fine.

## Tincan Trees

The meadows on the north side of the ridge are known as "Tincan Trees".
The terrain is composed of many small lumps and rollovers, with a mix of open meadows
and dense stands of trees, with tight passages connecting the meadows.
There are many complex mini drainages and ridges, so if you are adventurous you can
often find less-touched snow if you venture out of the obvious runs.
The laps are fairly short, maybe 800 vertical feet, but the uptrack is easy
so it doesn't feel totally stupid.

If the weather is stormy, Tincan is one of the better options in Turnagain pass.
This area has enough trees to provide visual contrast,
where many other areas would be whiteout conditions.

It is fairly easy to stay in low angle terrain, out of avalanche terrain,
but if you are careless it also is very possible to ski over a small
but steep and abrupt rollover and trigger a slide in high avalanche conditions,
eg if you are skiing in the middle of a storm.
These would be small, but with terrain traps, or if your partners aren't watching you,
it could be serious.
On many storm days I have seen small slides triggered in this zone.

## Tincan Common

This is the main, W facing bowl from the summit that faces straight at the parking lot.
You can skin straight to the top on the main uptrack, and it is easy to
do laps on this 800 foot {??} run.

## CFR (Cornice F#%$ing Run)

This goes from the summit of Tincan Common down the NW ridge,
the lefthand skyline when looking at Tincan from the parking lot.
This often is wind-affected, but when it has good snow, it is a
long, consistent, fairly safe run that is often overlooked and untouched.
I've only skied it once, usually I opt for lapping Tincan Common,
but it is a nice alternative to have in your back pocket.

## Todd's Run

This is the obvious, huge, steep NW facing bowl on the North side of Tincan ridge
that you see as drive up the pass from Anchorage.
It is named after Todd {???} who died
in an avalanche on {???} {link}.
It often avalanches naturally, and has a steep and committing entrance that makes it
hard to enter safely.
When it is safe though, it is an excellent steep run.
You get here by skinning the main uptrack to the top, and then booting back along the
ridge until you get to the dropin.